"""Optuna TPE tuning for the LightGBM baseline.

Objective: minimize nMAE on Fold-5 (2025 Q1), the direct surrogate for the
Q1-2026 leaderboard fold.

Secondary check: after each trial, also log nMAE on Fold-4 (2024 Q4) so we
can detect overfitting to the 2025-Q1 distribution.

Usage:
    python -m src.training.tune_lgbm --n-trials 80

Outputs:
- Best params written to ``configs/model/lgbm_tuned.yaml`` (YAML-like text).
- Full-trial study pickled to ``models/optuna_study.pkl``.
"""

from __future__ import annotations

import argparse
import pickle
import sys
from pathlib import Path

import numpy as np
import optuna
import pandas as pd
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.data.loaders import load_train
from src.data.schema import TARGET_COL, TIMESTAMP_COL
from src.data.splits import default_folds, split_indices
from src.eval.metrics import normalized_mae
from src.features.pipeline import build_features, feature_columns
from src.models.lightgbm_model import LGBMConfig, predict_lgbm, train_lgbm
from src.utils.seeding import set_global_seed

TRAIN_PATH = _ROOT / "data" / "raw" / "train_dataset.csv"
STUDY_PATH = _ROOT / "models" / "optuna_study.pkl"
CONFIG_OUT = _ROOT / "configs" / "model" / "lgbm_tuned.yaml"


def _prepare() -> tuple[pd.DataFrame, list[str]]:
    set_global_seed(42)
    df = load_train(TRAIN_PATH)
    df = build_features(df)
    feat_cols = feature_columns(df)
    return df, feat_cols


def _make_splits(df: pd.DataFrame) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Return train/val idx for the two most recent (and most relevant) folds."""
    folds = {f.name: f for f in default_folds()}
    return {
        "fold4_2024Q4": split_indices(df, folds["fold4_2024Q4"]),
        "fold5_2025Q1": split_indices(df, folds["fold5_2025Q1"]),
    }


def _evaluate(
    params: dict,
    df: pd.DataFrame,
    feat_cols: list[str],
    splits: dict[str, tuple[np.ndarray, np.ndarray]],
    config_template: LGBMConfig,
) -> tuple[float, float]:
    """Train on Fold-5 and Fold-4; return (fold5_nmae, fold4_nmae)."""
    results = {}
    for name, (train_idx, val_idx) in splits.items():
        X_tr = df.iloc[train_idx][feat_cols].to_numpy(dtype=np.float32)
        y_tr = df.iloc[train_idx][TARGET_COL].to_numpy(dtype=np.float32)
        X_va = df.iloc[val_idx][feat_cols].to_numpy(dtype=np.float32)
        y_va = df.iloc[val_idx][TARGET_COL].to_numpy(dtype=np.float32)

        # Build config with Optuna-proposed params.
        kwargs = {**config_template.__dict__, **params}
        cfg = LGBMConfig(**kwargs)

        booster = train_lgbm(X_tr, y_tr, X_va, y_va, feature_names=feat_cols, config=cfg)
        preds = predict_lgbm(booster, X_va)
        results[name] = normalized_mae(y_va, preds)

    return results["fold5_2025Q1"], results["fold4_2024Q4"]


def objective_factory(
    df: pd.DataFrame, feat_cols: list[str], splits: dict, template: LGBMConfig
):
    def objective(trial: optuna.Trial) -> float:
        params = {
            "num_leaves": trial.suggest_int("num_leaves", 31, 511),
            "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 10, 200, log=True),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
            "feature_fraction": trial.suggest_float("feature_fraction", 0.5, 1.0),
            "bagging_fraction": trial.suggest_float("bagging_fraction", 0.5, 1.0),
            "bagging_freq": trial.suggest_int("bagging_freq", 1, 10),
            "lambda_l1": trial.suggest_float("lambda_l1", 1e-4, 10.0, log=True),
            "lambda_l2": trial.suggest_float("lambda_l2", 1e-4, 10.0, log=True),
        }
        fold5, fold4 = _evaluate(params, df, feat_cols, splits, template)
        trial.set_user_attr("fold4_nmae", fold4)
        trial.set_user_attr("fold5_nmae", fold5)
        # Primary objective = fold5 (direct Q1 surrogate).
        # Add small penalty for fold4 to discourage overfitting to 2025.
        return 0.85 * fold5 + 0.15 * fold4

    return objective


def _write_yaml(path: Path, params: dict, nmae_fold5: float, nmae_fold4: float) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by tune_lgbm.py — do not edit by hand.",
        f"# Best Fold-5 nMAE: {nmae_fold5:.4f} %",
        f"# Best Fold-4 nMAE: {nmae_fold4:.4f} %",
        "",
    ]
    for k, v in params.items():
        if isinstance(v, float):
            lines.append(f"{k}: {v:.6g}")
        else:
            lines.append(f"{k}: {v}")
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Best params written to {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Optuna TPE tuning for LightGBM baseline.")
    parser.add_argument("--n-trials", type=int, default=80)
    parser.add_argument("--timeout", type=int, default=None, help="Seconds.")
    args = parser.parse_args()

    df, feat_cols = _prepare()
    splits = _make_splits(df)

    template = LGBMConfig(
        num_boost_round=2000,  # cap; early stopping controls real length
        early_stopping_rounds=150,
        verbose=-1,
        log_period=0,  # silence LightGBM per-iteration output during trials
    )
    # Reduce per-trial log spam.
    import lightgbm as lgb  # noqa: F401 — ensure import path is warm
    import logging

    logging.getLogger("lightgbm").setLevel(logging.WARNING)

    # Silence Optuna's per-trial INFO log; we use our own concise callback.
    optuna.logging.set_verbosity(optuna.logging.WARNING)

    sampler = TPESampler(seed=42, multivariate=True)
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=0)
    study = optuna.create_study(
        direction="minimize",
        sampler=sampler,
        pruner=pruner,
    )

    def _callback(study: optuna.Study, trial: optuna.FrozenTrial) -> None:
        fold5 = trial.user_attrs.get("fold5_nmae", float("nan"))
        fold4 = trial.user_attrs.get("fold4_nmae", float("nan"))
        print(
            f"  trial {trial.number:3d}  objective={trial.value:.4f}  "
            f"fold5={fold5:.4f}  fold4={fold4:.4f}  best_so_far={study.best_value:.4f}"
        )
    # Monkey-patch train_lgbm to silence per-trial LightGBM output is fiddly;
    # instead we temporarily replace its log callback. Simpler: set verbose=-1
    # (already done) and accept the early_stopping banner.

    obj = objective_factory(df, feat_cols, splits, template)
    print(f"Running {args.n_trials} Optuna trials...")
    study.optimize(obj, n_trials=args.n_trials, timeout=args.timeout, callbacks=[_callback])

    print(f"\n  Best objective: {study.best_value:.4f} %")
    print(f"  Best trial:     {study.best_trial.number}")
    print(f"  Best fold5:     {study.best_trial.user_attrs['fold5_nmae']:.4f} %")
    print(f"  Best fold4:     {study.best_trial.user_attrs['fold4_nmae']:.4f} %")
    print("  Best params:")
    for k, v in study.best_params.items():
        print(f"    {k}: {v}")

    # Persist study + params.
    STUDY_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(STUDY_PATH, "wb") as fh:
        pickle.dump(study, fh)
    print(f"  Study pickled to {STUDY_PATH}")

    _write_yaml(
        CONFIG_OUT,
        study.best_params,
        study.best_trial.user_attrs["fold5_nmae"],
        study.best_trial.user_attrs["fold4_nmae"],
    )


if __name__ == "__main__":
    main()
